version: "3.2"

networks:
  kotmijn-network:

services:
  kotnijn:
    restart: unless-stopped
    build:
      context: .
    depends_on:
      - rabbitmq
    networks:
      - kotmijn-network

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - kotmijn-network

