version: "3.2"

services:
  kotnijn:
    restart: unless-stopped
    build:
      context: .
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"

